services:
  - type: web
    name: amplicon-coverage-analyzer
    env: python
    buildCommand: |
      # Update apt and install OS packages
      apt-get update && apt-get install -y \
        wget \
        bzip2 \
        build-essential \
        zlib1g-dev \
        libbz2-dev \
        liblzma-dev \
        libcurl4-openssl-dev \
        libncurses5-dev \
        libncursesw5-dev \
        autoconf \
        make \
        git

      # Install samtools
      wget https://github.com/samtools/samtools/releases/download/1.18/samtools-1.18.tar.bz2
      tar -xjf samtools-1.18.tar.bz2
      cd samtools-1.18
      ./configure --prefix=/usr/local
      make
      make install
      cd ..

      # Install minimap2
      git clone https://github.com/lh3/minimap2.git
      cd minimap2
      make
      cp minimap2 /usr/local/bin/
      cd ..

      # Install Python dependencies
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.enableCORS false

